server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/_sweeter
    username: root
    password: deneme123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true